<?php

use \Drupal\stripe_payment\CreditCardController;

/**
 * Implements hook_payment_method_controller_info().
 */
function stripe_payment_payment_method_controller_info() {
  return array(
    'stripe_payment_credit_card' => '\Drupal\stripe_payment\CreditCardController',
  );
}

/**
* Implements hook_libraries_info().
*
* for stripes php wrapper library.
*/
function stripe_payment_libraries_info() {
  $libraries['stripe-php'] = array(
    'name' => 'Stripe',
    'vendor url' => 'https://stripe.com//',
    'download url' => 'https://github.com/stripe/stripe-php',
    'version arguments' => array(
      'file' => 'VERSION',
      'pattern' => '/([0-9\.]+)/',
      'lines' => 1
    ),
    'xautoload' => function($adapter) {
       $adapter->composerJson('composer.json');
    },
  );
  return $libraries;
}
