<?php

use \Drupal\stripe_payment\CreditCardController;

/**
 * Implements hook_payment_method_controller_info().
 */
function stripe_payment_payment_method_controller_info() {
  return array(
    'stripe_payment_credit_card' => '\Drupal\stripe_payment\CreditCardController',
  );
}

/**
* Implements hook_libraries_info().
*
* for stripes php wrapper library.
*/
function stripe_payment_libraries_info() {
  $libraries['stripe-php'] = array(
    'name' => 'Stripe',
    'vendor url' => 'https://stripe.com//',
    'download url' => 'https://github.com/stripe/stripe-php',
    'version arguments' => array(
      'file' => 'VERSION',
      'pattern' => '/([0-9\.]+)/',
      'lines' => 1
    ),
    'xautoload' => function($adapter) {
       $adapter->composerJson('composer.json');
    },
  );
  return $libraries;
}

/*
 * Implements hook_webform_client_form_alter().
 *
 * Attach stripe vendor js to forms.
 */
function stripe_payment_form_webform_client_form_alter(&$form, &$form_state, $form_id) {
  // TODO: restrict, e.g. attach js only to forms that have a Stripe payment method or
  //       at least any payment method (node type is not necessarily called "donation"!)
  $form['#attached']['js']['https://js.stripe.com/v3/'] = ['type' => 'external'];
}
